/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Cat(props: any) {
    const { nodes, materials } = useGLTF('/models/Cat.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ORIGAMI_Chat_1.geometry}
                    material={materials.wire_115115115}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.ORIGAMI_Chat_2.geometry}
                    material={materials['Material.001']}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/Cat.glb')