/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { Group } from 'three'

export default function Snoopy(props: any) {
  const { nodes, materials } = useGLTF('/models/snoopy.glb')
  const groupRef = useRef<Group>(null)

  // Animación en cada frame - solo rotación en Y
  // Animación compuesta: Rotación base + Flotar (Idle) + Balanceo
  useFrame((state, delta) => {
    if (groupRef.current) {
      const t = state.clock.getElapsedTime()

      // 1. Rotación continua suave (giro sobre sí mismo)
      groupRef.current.rotation.y += delta * 0.2

      // 2. Flotar arriba/abajo (Idle Animation)
      // Math.sin(t) va de -1 a 1. Multiplicamos por 0.1 para que sea sutil (10cm)
      // Sumamos 0.5 para que no se hunda en el suelo si el origen está en 0
      groupRef.current.position.y = Math.sin(t * 2) * 0.1

      // 3. Balanceo lateral (como si caminara o se meciera)
      groupRef.current.rotation.z = Math.cos(t * 2) * 0.05
    }
  })

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group position={[0, 1.2, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_1.geometry}
          material={materials.eyes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_2.geometry}
          material={materials.eyebrows}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_3.geometry}
          material={materials.skin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_4.geometry}
          material={materials.nose}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_5.geometry}
          material={materials.ears}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_6.geometry}
          material={materials.collar}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/snoopy.glb')