/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Window(props) {
  const { nodes, materials } = useGLTF('/models/window.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.092, 0, 4.085]} rotation={[Math.PI / 2, 0, 0]} scale={3.646}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Windows_Sill.geometry}
          material={materials.Wood_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Windows_Sill_1.geometry}
          material={materials.Plastic_Handle_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Windows_Sill_2.geometry}
          material={materials.Glass_material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/window.glb')
