/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { Mesh } from 'three'

export default function Snoopy(props: any) {
  const { nodes, materials } = useGLTF('/snoopy.glb')
  const meshRef = useRef<Mesh>(null)

  // Animación en cada frame
    useFrame((state, delta) => {
      if (meshRef.current) {
        meshRef.current.rotation.y += delta * 0.5
        meshRef.current.rotation.x += delta * 0.2
      }
    })

  return (
    <group {...props} dispose={null} ref={meshRef}>
      <group position={[0, 1.2, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_1.geometry}
          material={materials.eyes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_2.geometry}
          material={materials.eyebrows}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_3.geometry}
          material={materials.skin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_4.geometry}
          material={materials.nose}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_5.geometry}
          material={materials.ears}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.snoopyobj_6.geometry}
          material={materials.collar}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/snoopy.glb')