/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Table(props) {
  const { nodes, materials } = useGLTF('/models/Table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_7.geometry}
        material={materials.Table_7_mat}
        rotation={[Math.PI / 2, 0, 0]}
        scale={4.001}
      />
    </group>
  )
}

useGLTF.preload('/models/Table.glb')
